import type { PageData, Variety } from "@/lib/types"

function packet(
  variety: Omit<Variety, "href" | "image"> & { href?: string; image?: string },
): Variety {
  return {
    ...variety,
    href: variety.href ?? `/varieties/${variety.slug}`,
    image: variety.image ?? `/varieties/${variety.slug}.jpg`,
  }
}

const varieties = {
  tomato: packet({
    _id: "var-icehouse",
    title: "Icehouse Tomato",
    latin: "Solanum lycopersicum",
    slug: "icehouse-tomato",
    family: "Tomato",
    days: "78 days",
    sowing: "Start indoors 6 weeks before last frost",
    packet: "$4.50 · 40 seed",
    flavor: "Thin skin, cool-night acid, eat over the sink",
    isolation: "20 ft from other tomatoes; we grow one slicing type",
    use: "Fresh · sandwiches · a fast sauce",
    stock: "In the shed",
    plate: "#7A2E2E",
    sort: 1,
    story:
      "Saved from a cold frame in Tivoli since 1998. Sets fruit in cool nights when supermarket types stall. Skin is thin; eat over the sink.",
  }),
  paste: packet({
    _id: "var-brickyard",
    title: "Brickyard Paste",
    latin: "Solanum lycopersicum",
    slug: "brickyard-paste",
    family: "Tomato",
    days: "82 days",
    sowing: "Start with Icehouse; same tray, same mat",
    packet: "$4.50 · 40 seed",
    flavor: "Dry, dense, almost no water — sauce in an hour",
    isolation: "Same plot as Icehouse; we accept a little mixing",
    use: "Sauce · paste · dried halves",
    stock: "In the shed",
    plate: "#5C1818",
    sort: 2,
    story:
      "From a row behind the old brickyard on Broadway. Meatier than Icehouse, fewer seeds, the one we put up in August. Not a sandwich tomato. Do not ask it to be.",
  }),
  pepper: packet({
    _id: "var-widow",
    title: "Widow's Pepper",
    latin: "Capsicum annuum",
    slug: "widows-pepper",
    family: "Pepper",
    days: "85 days",
    sowing: "Start indoors with bottom heat",
    packet: "$4.25 · 25 seed",
    flavor: "Sweet, then a slow warmth — frying pepper, not a trophy",
    isolation: "30 ft; we do not grow hot peppers on the farm",
    use: "Fry with Icehouse · pickle rings",
    stock: "Limited",
    plate: "#C45A28",
    sort: 3,
    story:
      "A squat frying pepper, not a trophy. Ripens from pale green to brick. We fry it with the Icehouse in August.",
  }),
  cucumber: packet({
    _id: "var-blackriver",
    title: "Black River Cucumber",
    latin: "Cucumis sativus",
    slug: "black-river-cucumber",
    family: "Cucumber",
    days: "55 days",
    sowing: "Direct after frost, or two weeks indoors in peat",
    packet: "$3.75 · 30 seed",
    flavor: "Crisp, low bitterness even in heat",
    isolation: "One cucumber. We do not grow picklers.",
    use: "Slicing · a crock of spears if you must",
    stock: "In the shed",
    plate: "#3D6B45",
    sort: 4,
    story:
      "A ridge slicer from gardens along the Black River before the name meant a valley brand. Holds on the vine without puffing. Trellis it or it will take the path.",
  }),
  squash: packet({
    _id: "var-lantern",
    title: "Lantern Squash",
    latin: "Cucurbita maxima",
    slug: "lantern-squash",
    family: "Squash",
    days: "100 days",
    sowing: "Hill after frost; two plants per mound",
    packet: "$4.00 · 15 seed",
    flavor: "Dry, sweet, maple and pie",
    isolation: "Far from the neighbor's zucchini; we watch the bees",
    use: "Storage · roast · pie",
    stock: "In the shed",
    plate: "#C4722A",
    sort: 5,
    story:
      "Stores in a cool pantry until March. Flesh is dry and sweet — pie, or cubes roasted with maple.",
  }),
  melon: packet({
    _id: "var-esopus",
    title: "Esopus Melon",
    latin: "Cucumis melo",
    slug: "esopus-melon",
    family: "Melon",
    days: "88 days",
    sowing: "Hill after the nights stay above 55°F",
    packet: "$4.25 · 20 seed",
    flavor: "Green flesh, not musk-heavy, a clean finish",
    isolation: "Do not plant next to Black River; they will talk",
    use: "Breakfast · a salt slice in the field",
    stock: "Limited",
    plate: "#D4A54A",
    sort: 6,
    story:
      "Named for the creek, not the town brand. Green-fleshed, netted lightly, it wants heat we do not always get. In a dry July it is the best thing on the farm. In a wet one, pick early and do not apologize.",
  }),
  bean: packet({
    _id: "var-crows",
    title: "Crow's Beak Bean",
    latin: "Phaseolus vulgaris",
    slug: "crows-beak-bean",
    family: "Bean",
    days: "62 days",
    sowing: "Direct sow after the soil hits 60°F",
    packet: "$3.75 · 50 seed",
    flavor: "Nutty dry, sweet at finger length",
    isolation: "North field only; one dry bean on the farm",
    use: "Dry soup · fresh filet",
    stock: "In the shed",
    plate: "#B08948",
    sort: 7,
    story:
      "A pole bean with a hooked tip the farm kids named. Dry it for soup or pick at finger length. One packet covers a ten-foot trellis.",
  }),
  pea: packet({
    _id: "var-pastor",
    title: "Pastor's Pea",
    latin: "Pisum sativum",
    slug: "pastors-pea",
    family: "Pea",
    days: "58 days",
    sowing: "As soon as the ground can be worked",
    packet: "$3.50 · 80 seed",
    flavor: "Sweet shelling pea; not a snap, not a snow",
    isolation: "Spring only; we do not save a fall crop",
    use: "Shelling · a short freezer bag",
    stock: "In the shed",
    plate: "#7B8F3A",
    sort: 8,
    story:
      "A shelling pea from a church garden in Red Hook that outlived the pastor. Sow it when you are tired of winter. It does not wait for polite weather. Trellis with brush, not cattle panel.",
  }),
  kale: packet({
    _id: "var-mile",
    title: "Mile Marker Kale",
    latin: "Brassica oleracea",
    slug: "mile-marker-kale",
    family: "Brassica",
    days: "55 days",
    sowing: "Sow mid-July for fall; sweeter after frost",
    packet: "$3.50 · 200 seed",
    flavor: "Sweet after frost, cabbage otherwise",
    isolation: "Hold until the tomatoes are done; do not let it flower near anything",
    use: "Fall greens · a December soup",
    stock: "In the shed",
    plate: "#2C4A32",
    sort: 9,
    story:
      "Named for the milepost on Route 9G where we first gleaned it. Holds in the field through December under row cover.",
  }),
  lettuce: packet({
    _id: "var-shore",
    title: "Shoreline Lettuce",
    latin: "Lactuca sativa",
    slug: "shoreline-lettuce",
    family: "Greens",
    days: "48 days",
    sowing: "Succession sow every 10 days in spring",
    packet: "$3.25 · 500 seed",
    flavor: "Mild looseleaf, no bitterness at the first warm spell",
    isolation: "Spring beds only; we do not let it bolt for seed next to the kale",
    use: "Cut-and-come-again · bowls until July",
    stock: "In the shed",
    plate: "#8FA86A",
    sort: 10,
    story:
      "Looseleaf that does not bolt at the first warm spell. Cut-and-come-again from the same row until July.",
  }),
  chard: packet({
    _id: "var-hollow",
    title: "Hollow Stem Chard",
    latin: "Beta vulgaris",
    slug: "hollow-stem-chard",
    family: "Greens",
    days: "55 days",
    sowing: "Direct in May, or start a tray with the tomatoes",
    packet: "$3.50 · 80 seed",
    flavor: "Earthy leaf, stems like a mild beet",
    isolation: "Keep off the River Road beet if you save seed",
    use: "Greens all summer · stems in a pan",
    stock: "In the shed",
    plate: "#8B2E3A",
    sort: 11,
    story:
      "Red stems you can see from the road. The leaf stands heat better than Shoreline. We cut it twice a week from June until the frost that seasons the kale.",
  }),
  celery: packet({
    _id: "var-cutting",
    title: "Cutting Celery",
    latin: "Apium graveolens",
    slug: "cutting-celery",
    family: "Greens",
    days: "80 days",
    sowing: "Start indoors 10 weeks out; it is slow and worth it",
    packet: "$3.75 · 200 seed",
    flavor: "Leaf celery — soup, not a crudité",
    isolation: "One celery. Do not plant next to parsley you intend to save.",
    use: "Stock · fine chop · a little goes far",
    stock: "Limited",
    plate: "#6B8F5A",
    sort: 12,
    story:
      "Not Pascal. Not a supermarket bunch. Leaf and thin stem, the kind a kitchen uses by the pinch. Start it early. Forget it in the tray and it will still be there, smaller than you wanted, still good.",
  }),
  carrot: packet({
    _id: "var-tivoli",
    title: "Tivoli Carrot",
    latin: "Daucus carota",
    slug: "tivoli-carrot",
    family: "Root",
    days: "72 days",
    sowing: "Direct, early spring and again in July for winter",
    packet: "$3.50 · 400 seed",
    flavor: "True carrot, not candy — a little spice",
    isolation: "Biennial; we root-to-seed a marked row",
    use: "Fresh · cellar · a winter stew",
    stock: "In the shed",
    plate: "#C45C1C",
    sort: 13,
    story:
      "An orange Nantes type that actually makes a root in our clay if you work in sand. The July sowing is the one we eat in January. Thin like you mean it.",
  }),
  beet: packet({
    _id: "var-river",
    title: "River Road Beet",
    latin: "Beta vulgaris",
    slug: "river-road-beet",
    family: "Root",
    days: "58 days",
    sowing: "Direct April and August",
    packet: "$3.50 · 100 seed",
    flavor: "Sweet earth, greens you should not throw away",
    isolation: "Keep off Hollow Stem if you save seed",
    use: "Roast · pickle · tops in the pan",
    stock: "In the shed",
    plate: "#5C1A2E",
    sort: 14,
    story:
      "A round red beet that does not get woody if you leave it. The name is the road, not a romance. Sow a short row twice. Eat the tops. That is the whole crop.",
  }),
  radish: packet({
    _id: "var-freight",
    title: "Fast Freight Radish",
    latin: "Raphanus sativus",
    slug: "fast-freight-radish",
    family: "Root",
    days: "24 days",
    sowing: "Every two weeks in spring; stop in heat",
    packet: "$3.00 · 300 seed",
    flavor: "Hot at the shoulder, mild at the tip",
    isolation: "Do not let it flower next to the kale",
    use: "Spring bunches · a quick pickle",
    stock: "In the shed",
    plate: "#C44A5A",
    sort: 15,
    story:
      "Named for the freight that used to run through Tivoli: it does not wait. Twenty-four days, a red globe, then it is pith if you hesitate. Sow it between the peas. Pull it before the tomatoes go out.",
  }),
  onion: packet({
    _id: "var-stone",
    title: "Stone Fence Onion",
    latin: "Allium cepa",
    slug: "stone-fence-onion",
    family: "Allium",
    days: "110 days from sow",
    sowing: "Start indoors in February; transplant as pencils",
    packet: "$4.00 · 150 seed",
    flavor: "Storage onion, not a sweet — it lasts",
    isolation: "We grow one onion. Flowering is for next year's seed.",
    use: "Storage · the winter kitchen",
    stock: "Limited",
    plate: "#C4A070",
    sort: 16,
    story:
      "A long-day storage onion that earns the extra weeks. Hang it in the shed until the necks are tight. It will sit in a crate until March if you cured it. Seed, not sets. Sets are someone else's work.",
  }),
  corn: packet({
    _id: "var-ninemile",
    title: "Nine-Mile Flint",
    latin: "Zea mays",
    slug: "nine-mile-flint",
    family: "Corn",
    days: "105 days",
    sowing: "Direct when the oak leaves are the size of a mouse ear",
    packet: "$4.50 · 80 seed",
    flavor: "Dry flint for meal — not a sweet corn",
    isolation: "A quarter mile from sweet corn, or do not bother saving",
    use: "Meal · polenta · a winter porridge",
    stock: "Wait list",
    plate: "#C4A028",
    sort: 17,
    story:
      "Flint, not sugar. We grind it in January. Isolation is the hard part on four acres; we plant it in the far rectangle and ask the neighbor not to put in a roadside sweet. If you want corn on the cob, this is the wrong packet.",
  }),
}

const catalog = [
  varieties.tomato,
  varieties.paste,
  varieties.pepper,
  varieties.cucumber,
  varieties.squash,
  varieties.melon,
  varieties.bean,
  varieties.pea,
  varieties.kale,
  varieties.lettuce,
  varieties.chard,
  varieties.celery,
  varieties.carrot,
  varieties.beet,
  varieties.radish,
  varieties.onion,
  varieties.corn,
]

const notes = [
  {
    _id: "j1",
    title: "Why we still start tomatoes in the icehouse",
    slug: "tomatoes-in-the-icehouse",
    excerpt: "The building is a ruin with good light. That is the whole method.",
    season: "March",
    href: "/journal/tomatoes-in-the-icehouse",
    sort: 1,
    body: "The icehouse lost its roof in 1986. What it kept is south light and a stone floor that stays cold until May. We set the first Icehouse trays there because the kitchen windows fog and the packing shed is full of bags.\n\nHeat mats on the benches, a fan on low so the seedlings do not damp off, and a door we prop with a brick. That is the method. People want a greenhouse. We have a ruin that works.\n\nIf you start tomatoes in a spare bedroom, you are doing the same job. Keep them cool at night. Do not chase height.",
  },
  {
    _id: "j2",
    title: "Saving Crow's Beak without mixing the plot",
    slug: "saving-crows-beak",
    excerpt: "Isolation distance on a four-acre farm is a story we tell ourselves. Here is what we actually do.",
    season: "September",
    href: "/journal/saving-crows-beak",
    sort: 2,
    body: "Beans outcross if you let them. The catalog number for isolation is a number written for people with a section and a hedgerow. We have four acres and a neighbor who plants supermarket pole beans for fun.\n\nWe grow one dry bean. Crow's Beak, north field, far from the road. We walk the row before flower and pull anything with a straight tip. We do not save from the trellis nearest the fence.\n\nIf you grow another bean, eat it. Do not let it go to seed next to this one. That is the contract.",
  },
  {
    _id: "j3",
    title: "A frost that taught us the kale's name",
    slug: "frost-and-the-kale",
    excerpt: "We left a row uncovered on a dare. It was better in December than in August.",
    season: "December",
    href: "/journal/frost-and-the-kale",
    sort: 3,
    body: "Mile Marker was a roadside plant before it was a packet. We took seed from a row that had been through a hard freeze without cover, because that was the row we still wanted to eat.\n\nAugust kale is cabbage with worse manners. December kale, after frost, is the reason we bother. Sugar in the leaf, less bite, a color that looks like it means it.\n\nSow it late. Do not baby it. If you only know kale from a bag in July, wait until the first real cold and try this one.",
  },
  {
    _id: "j4",
    title: "How a packet leaves the shed",
    slug: "how-a-packet-leaves",
    excerpt: "We do not run a cart. We weigh, write, and tape. Here is the week a packet is made.",
    season: "February",
    href: "/journal/how-a-packet-leaves",
    sort: 4,
    body: "Seed is stored in the metal cabinet that used to hold paint. In February we pull jars, check germination on a wet paper in the kitchen, and throw out anything that cannot make eight in ten.\n\nPackets are kraft, stamped with a rubber date, filled on the scale by the window. Forty Icehouse seed is not a guess. If a jar is light we mark the variety Limited and we do not apologize in the catalog copy.\n\nWe ship March through June because summer is for the field. A packet that sits in a hot truck in July is not our work anymore.",
  },
  {
    _id: "j5",
    title: "The Esopus melon and a wet July",
    slug: "esopus-in-a-wet-july",
    excerpt: "Melons on four acres in the Hudson Valley are a bet. Some years we lose it in public.",
    season: "July",
    href: "/journal/esopus-in-a-wet-july",
    sort: 5,
    body: "Esopus wants heat we advertise more than we have. In a dry year the vines run and the fruit nets. In a wet July the flowers abort and we eat cucumbers instead, which is not a failure unless you promised a melon.\n\nWe still grow it because the year it works, there is nothing in the supermarket that tastes like that creek. Pick at the slip. Do not wait for a perfume that may not come.\n\nIf your summers are reliably hot, pull our dates forward. If they are like ours, plant two hills and keep the cucumber.",
  },
  {
    _id: "j6",
    title: "Flint corn is not a cob",
    slug: "flint-corn-is-not-a-cob",
    excerpt: "Nine-Mile is meal. People still write us asking when to butter it.",
    season: "October",
    href: "/journal/flint-corn-is-not-a-cob",
    sort: 6,
    body: "We put flint in the catalog because a farm that only sells salad is not telling the truth about winter. Nine-Mile dries on the stalk. We husk in October, hang in the shed, shell after Christmas, mill when we want porridge.\n\nIsolation is the reason the packet says Wait list. Four acres and a roadside sweet corn is a cross waiting to happen. Some years we do not save. Some years we ask a neighbor for a quarter mile of manners.\n\nIf you want corn on the cob, buy sugar seed from someone else. If you want meal that tastes like a field, this is the packet.",
  },
]

const workshops = [
  {
    _id: "w1",
    title: "Soil blocks and the spring tray",
    date: "14 March 2026",
    place: "Packing shed",
    notes: "Make mix, fill, sow Icehouse and Brickyard. Take a tray home.",
    seats: "12",
    sort: 1,
  },
  {
    _id: "w2",
    title: "Reading a seed packet like a contract",
    date: "4 April 2026",
    place: "Kitchen table",
    notes: "Days to maturity, isolation, and why heirloom is not a guarantee.",
    seats: "12",
    sort: 2,
  },
  {
    _id: "w3",
    title: "Peas, radishes, and the first outdoor row",
    date: "18 April 2026",
    place: "North field",
    notes: "Sow Pastor's Pea and Fast Freight. Bring a trowel.",
    seats: "12",
    sort: 3,
  },
  {
    _id: "w4",
    title: "Transplanting the icehouse trays",
    date: "23 May 2026",
    place: "South beds",
    notes: "Harden off, plant, water in. Widow's Pepper goes out the same day.",
    seats: "10",
    sort: 4,
  },
  {
    _id: "w5",
    title: "Dry bean harvest and the Crow's Beak",
    date: "19 September 2026",
    place: "North field",
    notes: "Pull, thresh, winnow. Leave with a jar.",
    seats: "12",
    sort: 5,
  },
  {
    _id: "w6",
    title: "Squash cure and the flint hang",
    date: "10 October 2026",
    place: "Packing shed",
    notes: "Lantern in crates, Nine-Mile on the rafters. How we store winter.",
    seats: "10",
    sort: 6,
  },
]

export const seed: PageData = {
  source: "fallback",
  settings: {
    siteName: "Thorn & Furrow",
    place: "Hudson Valley, New York",
    nav: [
      { label: "The catalog", href: "/#catalog" },
      { label: "Varieties", href: "/varieties" },
      { label: "Journal", href: "/journal" },
      { label: "Workshops", href: "/workshops" },
      { label: "The farm", href: "/about" },
    ],
    cta: { label: "Request a packet list", href: "/order", style: "primary", eventId: "nav_order" },
    footerNote: "We ship seed March through June. Packets are packed on the farm the week they leave.",
    defaultSeo: {
      title: "Thorn & Furrow — heirloom seed from the Hudson Valley",
      description:
        "Seventeen varieties we still grow out ourselves, plus a seasonal journal and workshops at the farm in Tivoli.",
    },
  },
  home: {
    seo: {
      title: "Thorn & Furrow — Catalog No. 14, Spring 2026",
      description:
        "Icehouse tomato through Nine-Mile flint. Seed packed on the farm in Tivoli, New York.",
    },
    sections: [
      {
        _type: "masthead",
        _key: "masthead",
        catalogNo: "No. 14",
        season: "Spring 2026",
        heading: "Seed we still grow out ourselves",
        deck: "Seventeen varieties this season. No fillers, no ornamental packets of things we do not plant. If it is in the catalog, it is in the ground on River Road.",
        primaryCta: { label: "Request a packet list", href: "/order", eventId: "hero_order" },
      },
      {
        _type: "featuredVariety",
        _key: "featured",
        kicker: "This season's lead",
        variety: varieties.tomato,
      },
      {
        _type: "sowingTable",
        _key: "sowing",
        heading: "What to sow from this desk, this month",
        intro: "Written for zone 6a, late March. If you are south of us, pull dates forward a week. North, wait for the soil.",
        rows: [
          { crop: "Icehouse Tomato", window: "Now, indoors", method: "Heat mat, 16-hour light" },
          { crop: "Brickyard Paste", window: "Now, indoors", method: "Same tray as Icehouse" },
          { crop: "Widow's Pepper", window: "Now, indoors", method: "Bottom heat; do not rush" },
          { crop: "Cutting Celery", window: "Now, indoors", method: "Surface sow; it is slow" },
          { crop: "Stone Fence Onion", window: "Now, indoors", method: "February sowing if you missed it" },
          { crop: "Pastor's Pea", window: "This week, outdoors", method: "As soon as the ground works" },
          { crop: "Fast Freight Radish", window: "This week, outdoors", method: "A short row between the peas" },
          { crop: "Shoreline Lettuce", window: "Next two weeks", method: "Direct, or soil blocks" },
          { crop: "Tivoli Carrot", window: "Next two weeks", method: "Direct; thin like you mean it" },
          { crop: "Crow's Beak Bean", window: "After last frost", method: "Direct on a trellis" },
          { crop: "Mile Marker Kale", window: "Hold until July", method: "Fall crop; do not start now" },
        ],
      },
      {
        _type: "varietyIndex",
        _key: "index",
        heading: "The spring list",
        intro: "Seventeen packets. Latin names first, the way a catalog should. Common names we use in the field follow.",
        varieties: catalog,
      },
      {
        _type: "journalStrip",
        _key: "journal",
        heading: "From the River Road notebook",
        notes,
      },
      {
        _type: "workshopList",
        _key: "workshops",
        heading: "Saturdays on the farm",
        intro: "Twelve people, the packing shed, coffee. Bring boots. We cancel if the driveway is ice.",
        workshops,
      },
      {
        _type: "letterCta",
        _key: "letter",
        heading: "We still pack by hand",
        body: "Write us with your zone and what you grew last year. Mark the packets you want. We will send a list — not a newsletter sequence.",
        primaryCta: { label: "Request a packet list", href: "/order", eventId: "footer_order" },
      },
    ],
  },
}
